spring:
  datasource:
    druid:
      driver-class-name: 'com.mysql.cj.jdbc.Driver'
      url: 'jdbc:mysql://localhost:3306/cloud_hospital?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&parseTime=true&allowPublicKeyRetrieval=true'
      username: 'root'
      password: 'root'
  mvc:
    dispatch-options-request: true
server:
  servlet:
    context-path: '/api' # 增加统一前缀
